### ISSUE TITLE
Payload inject falied Xiaomi 4X

### ISSUE THREAD

**Issue by Kronos2308** [MenosGrante/Rekado#104]
HI 
well i have tis problem with all apk injectors
never get to inject the payload for some reason
my phone has otg support and the cable is good i test with a tablet and pc and is ok
this is the log
![imagen](https://user-images.githubusercontent.com/36446521/126881977-4cfe9e0a-bb65-4d3c-ac27-946e6dd78b0e.png)

**Comment by MenosGrante** [comment]
Hey, I have described what this error means in the README of this repository, but will duplicate it here:

SUBMITURB

This problem occurs on devices with old USB controllers installed in their devices (EHCI/USB 2.0). This is a device-only problem, that can be fixed by installing additional kernel patches, which is not recommended to do yourself. Only devices with xHCI (USB 3.0) controllers are supported now.
