### ISSUE TITLE
Can't add "fusee.bin" to Payloads

### ISSUE THREAD

**Issue by MultiKoopa** [MenosGrante/Rekado#108]
in the latest Atmosphere, "fusee-primary.bin" has been renamed "fusee.bin", but Rekado won't allow me to add "fusee.bin" for some reason.

**Comment by MenosGrante** [comment]
I would recommend you fresh installing latest version of the Rekado.

**Comment by retrofank** [comment]
> in the latest Atmosphere, "fusee-primary.bin" has been renamed "fusee.bin", but Rekado won't allow me to add "fusee.bin" for some reason.

Here is the FIX for when AMS fusee.bin and Hekete get updates.  Connect your phone to the PC and navigate to the following directories:-

Android\Data\com.pavelrekun.rekado

You will find the installed payloads in that location, so just overwite the existing ones with the new versions (make sure they are named the same, as the ones you replace),  

That should fix any errors when AMS, gets updated, as fusee.bin always does.

**Comment by OrGoN3** [comment]
> > in the latest Atmosphere, "fusee-primary.bin" has been renamed "fusee.bin", but Rekado won't allow me to add "fusee.bin" for some reason.
> 
> Here is the FIX for when AMS fusee.bin and Hekete get updates. Connect your phone to the PC and navigate to the following directories:-
> 
> Android\Data\com.pavelrekun.rekado\files
> 
> You will find the installed payloads in that location, so just overwite the existing ones with the new versions (make sure they are named the same, as the ones you replace),
> 
> That should fix any errors when AMS, gets updated, as fusee.bin always does.

This also works. Just remember though, the version info will not be incremented if you do this. You still have to wait for the update on the back end.

I still don't understand why this isn't automated on the backend.
