### ISSUE TITLE
Sending payload failed at offset 155648 & 77824

### ISSUE THREAD

**Issue by SnoFox** [MenosGrante/Rekado#41]
Attempting to send [Hekate CTCaer 4.9.1](https://github.com/CTCaer/hekate/releases/tag/v4.9.1_) fails to send the payload. I've seen it fail at both offsets 155648 and 77824.

Environment:
Phone: Pixel 3
Cable: USB C to USB C
Rekado: 2.6.2 (37)
Payload: Hekate CTCaer 4.9.1

**Comment by MenosGrante** [comment]
Does any other payloads sending successfully?

**Comment by SnoFox** [comment]
Yep -- Fuse launches fine.

**Comment by speed47** [comment]
I also have this issue on my LG G4.
Some additional information: I've tried with Rekado 1.0.5, 2.5(30) and 2.6.5(40). The three fail exactly at the same offset with the same payload, so it doesn't seem to be a regression of some sort on the software.
As the offset involved is not that small (i.e. it's not 0), I wondered whether a smaller payload would work. So I compiled a stripped-down version of Hekate, taking up 74 Kb instead of 122 Kb. Then I tried to inject that, and ... it worked!
This explains why some smaller payloads might work: the problem here seems to happen for larger payload. For reference, the biggest payload that will work in RCM is 126296 bytes.

**Comment by speed47** [comment]
Good news: I found a workaround. Simply `Thread.sleep(250)` between each chunk sent through USB.
I could successfully send a 122 Kb payload with this modification.

**Comment by MenosGrante** [comment]
Thank you @speed47, I will check it later.

**Comment by MenosGrante** [comment]
My new Nintendo Switch should come in few days, then I will check this problem.

**Comment by MenosGrante** [comment]
As I said previously, this problem relates to cable of adapter you are using, not to software. Try to check another cable firstly and if you will have another related problems post in in another, similar discussion #9.
