### ISSUE TITLE
Please re-add the ability to hide pre-installed payloads

### ISSUE THREAD

**Issue by pixeltester** [MenosGrante/Rekado#74]
Please re-add this feature, I can't see any benefit in actually removing features from this app, very strange decision. How did you decide that it's not a popular feature? I for one use it.

Other than that thank you for the app, it's great.

**Comment by MenosGrante** [comment]
I am not sure, why do you need this feature? Most of the users uses only bundled payloads.

**Comment by pixeltester** [comment]
Custom/dev payloads which means I have duplicates in the list if you don't allow hide.

Users should be free to add their own payloads manually anyway.

**Comment by Clydefrosch22** [comment]
i would second that request, if it doesn't inconveniences you too much.

i usually set it up so only one payload is visible, because otherwise, i randomly click the wrong one every once in a while.
now i know there's the auto injector, but I don't like setting that up for the times when I have to use a different one after all.

**Comment by MenosGrante** [comment]
Added in the 4.1 update.
