### ISSUE TITLE
Auto-update doesn't work

### ISSUE THREAD

**Issue by iGom** [MenosGrante/Rekado#87]
![Screenshot_20200915-214546_Rekado](https://user-images.githubusercontent.com/4786772/93262918-ee1c1c80-f79c-11ea-848a-f53156269ac3.png)

**Comment by MenosGrante** [comment]
What exactly is not working for you?

**Comment by iGom** [comment]
Auto updates to newer version of payloads

**Comment by Sara06515** [comment]
They've been updated and the fusee_primary.bin for atmosphere 0.14.3. But it's still not updating consistantly because it hasn't auto-updated (even when I try to do this manually and pull down to refresh the payloads) fusee_primary.bin for atmosphere 0.14.4 yet.

Please fix when you can! Thank you so much and I really enjoy using this app! Works well and is very convenient!
